export const ADMIN_LIST_USERS_REQUEST = 'ADMIN_LIST_USERS_REQUEST';
export const ADMIN_LIST_USERS_SUCCESS = 'ADMIN_LIST_USERS_SUCCESS';
export const ADMIN_LIST_USERS_FAIL = 'ADMIN_LIST_USERS_FAIL';
export const ADMIN_LIST_USERS_RESET = 'ADMIN_LIST_USERS_RESET';

export const ADMIN_UPDATE_USER_REQUEST = 'ADMIN_UPDATE_USER_REQUEST';
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS';
export const ADMIN_UPDATE_USER_FAIL = 'ADMIN_UPDATE_USER_FAIL';
export const ADMIN_UPDATE_USER_RESET = 'ADMIN_UPDATE_USER_RESET';

export const ADMIN_DELETE_USER_REQUEST = 'ADMIN_DELETE_USER_REQUEST';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_FAIL = 'ADMIN_DELETE_USER_FAIL';

export const ADMIN_DELETE_PRODUCT_REQUEST = 'ADMIN_DELETE_PRODUCT_REQUEST';
export const ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS';
export const ADMIN_DELETE_PRODUCT_FAIL = 'ADMIN_DELETE_PRODUCT_FAIL';
export const ADMIN_DELETE_PRODUCT_RESET = 'ADMIN_DELETE_PRODUCT_RESET';
