export const ADMIN_LIST_USERS_REQUEST = 'ADMIN_LIST_USERS_REQUEST';
export const ADMIN_LIST_USERS_SUCCESS = 'ADMIN_LIST_USERS_SUCCESS';
export const ADMIN_LIST_USERS_FAIL = 'ADMIN_LIST_USERS_FAIL';
export const ADMIN_LIST_USERS_RESET = 'ADMIN_LIST_USERS_RESET';

export const ADMIN_UPDATE_USER_REQUEST = 'ADMIN_UPDATE_USER_REQUEST';
export const ADMIN_UPDATE_USER_SUCCESS = 'ADMIN_UPDATE_USER_SUCCESS';
export const ADMIN_UPDATE_USER_FAIL = 'ADMIN_UPDATE_USER_FAIL';
export const ADMIN_UPDATE_USER_RESET = 'ADMIN_UPDATE_USER_RESET';

export const ADMIN_DELETE_USER_REQUEST = 'ADMIN_DELETE_USER_REQUEST';
export const ADMIN_DELETE_USER_SUCCESS = 'ADMIN_DELETE_USER_SUCCESS';
export const ADMIN_DELETE_USER_FAIL = 'ADMIN_DELETE_USER_FAIL';

export const ADMIN_UPDATE_PRODUCT_REQUEST = 'ADMIN_UPDATE_PRODUCT_REQUEST';
export const ADMIN_UPDATE_PRODUCT_SUCCESS = 'ADMIN_UPDATE_PRODUCT_SUCCESS';
export const ADMIN_UPDATE_PRODUCT_FAIL = 'ADMIN_UPDATE_PRODUCT_FAIL';
export const ADMIN_UPDATE_PRODUCT_RESET = 'ADMIN_UPDATE_PRODUCT_RESET';

export const ADMIN_DELETE_PRODUCT_REQUEST = 'ADMIN_DELETE_PRODUCT_REQUEST';
export const ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS';
export const ADMIN_DELETE_PRODUCT_FAIL = 'ADMIN_DELETE_PRODUCT_FAIL';
export const ADMIN_DELETE_PRODUCT_RESET = 'ADMIN_DELETE_PRODUCT_RESET';

export const ADMIN_CREATE_PRODUCT_REQUEST = 'ADMIN_CREATE_PRODUCT_REQUEST';
export const ADMIN_CREATE_PRODUCT_SUCCESS = 'ADMIN_CREATE_PRODUCT_SUCCESS';
export const ADMIN_CREATE_PRODUCT_FAIL = 'ADMIN_CREATE_PRODUCT_FAIL';
export const ADMIN_CREATE_PRODUCT_RESET = 'ADMIN_CREATE_PRODUCT_RESET';

export const ADMIN_LIST_ORDERS_REQUEST = 'ADMIN_LIST_ORDERS_REQUEST';
export const ADMIN_LIST_ORDERS_SUCCESS = 'ADMIN_LIST_ORDERS_SUCCESS';
export const ADMIN_LIST_ORDERS_FAIL = 'ADMIN_LIST_ORDERS_FAIL';
export const ADMIN_LIST_ORDERS_RESET = 'ADMIN_LIST_ORDERS_RESET';

export const ADMIN_UPDATE_ORDER_TO_DELIVERED_REQUEST = 'ADMIN_UPDATE_ORDER_TO_DELIVERED_REQUEST';
export const ADMIN_UPDATE_ORDER_TO_DELIVERED_SUCCESS = 'ADMIN_UPDATE_ORDER_TO_DELIVERED_SUCCESS';
export const ADMIN_UPDATE_ORDER_TO_DELIVERED_FAIL = 'ADMIN_UPDATE_ORDER_TO_DELIVERED_FAIL';
export const ADMIN_UPDATE_ORDER_TO_DELIVERED_RESET = 'ADMIN_UPDATE_ORDER_TO_DELIVERED_RESET';
