export const CART_ADD_REQUEST = 'CART_ADD_REQUEST';
export const CART_REMOVE_REQUEST = 'CART_REMOVE_REQUEST';
export const CART_RESET = 'CART_RESET';
export const SHIPPING_ADDRESS_SAVE_REQUEST = 'SHIPPING_ADDRESS_SAVE_REQUEST';
export const PAYMENT_METHOD_SAVE_REQUEST = 'PAYMENT_METHOD_SAVE_REQUEST';
